services:
  flask:
    build: .
    container_name: automated-bash-script_flask
    restart: always
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production

  nginx:
    image: nginx:latest
    container_name: automated-bash-script_nginx
    depends_on:
      - flask
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:
    driver: bridge
